package com.litefix.models.md.enums;

public enum SessionRejectReason {
	  /*0  */ INVALID_TAG_NUMBER
	, /*1  */ REQUIRED_TAG_MISSING
	, /*2  */ TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE
	, /*3  */ UNDEFINED_TAG
	, /*5  */ VALUE_IS_INCORRECT
	, /*6  */ INCORRECT_DATA_FORMAT_FOR_VALUE
	, /*8  */ SIGNATURE_PROBLEM
	, /*10 */ SENDINGTIME_ACCURACY_PROBLEM
	, /*12 */ XML_VALIDATION_ERROR
	, /*13 */ TAG_APPEARS_MORE_THAN_ONCE
	, /*14 */ TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER
	, /*15 */ REPEATING_GROUP_FIELDS_OUT_OF_ORDER
	, /*16 */ INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP
	, /*99 */ OTHER
}
